export const EDITION = "ascent-2026";

export const IP_RATE_LIMIT_MAX_PER_HOUR = 10;
export const IDENTIFIER_RATE_LIMIT_MAX = 3;
export const IDENTIFIER_RATE_LIMIT_WINDOW_MS = 30 * 60 * 1000;

export const SEARCH_RATE_LIMIT_MAX_PER_MINUTE = 60;
export const SEARCH_RATE_LIMIT_WINDOW_MS = 60 * 1000;
