import type { Metadata } from "next";
import LegalPage from "@/components/legal/LegalPage";
import { TERMS_VERSION } from "@/content/legal";
export const metadata: Metadata = { title: "Competition terms | Ascent", description: "Terms for registering and participating in Ascent ’26." };
export default function TermsPage() {
  return <LegalPage title="Competition terms" version={TERMS_VERSION}>
    <section><h2>Organiser and scope</h2><p>Algorithms &amp; Mathematics Society (AMS), Mumbai, organises Ascent ’26. These terms cover this website, registration and participation. The <a href="/privacy">privacy policy</a> explains personal-data use. Candidate help and general enquiries go to <a href="mailto:team@amshq.in">team@amshq.in</a>; sponsorship enquiries go to <a href="mailto:partners@amshq.in">partners@amshq.in</a>.</p></section>
    <section><h2>Registration and qualification</h2><p>Registration is free. Submit accurate information and documents you are entitled to share. A receipt confirms that your entry was recorded; it does not confirm eligibility, selection, a seat or direct qualification. AMS may verify institution and education claims. An unverified claim does not grant automatic qualification.</p><p>Applicants under 18 should have a parent or guardian contact the support team before submitting personal data. Participation may require verified guardian permission and additional arrangements.</p></section>
    <section><h2>Format, dates and rules</h2><p>The competition has three rounds. See the <a href="/#timeline">published calendar</a> and <a href="/syllabus">syllabus</a> for the current plan. Round 3 is planned for Mumbai on a tentative date. Detailed compiler, hardware, measurement, permitted-tool and proctoring requirements will be published before the relevant round.</p><p>Valid solutions must remain correct. Performance rankings use the published measurement method. Do not assume an unpublished cutoff, tie-break, tool permission or result. Material schedule or rule changes will be announced on the website and communicated to affected entrants where practical.</p></section>
    <section><h2>Fair participation</h2><p>Use your own identity and follow each round’s rules for individual or team work. Do not impersonate another entrant, obtain unauthorised assistance, tamper with the judge, disrupt services or submit automated registrations. AMS may investigate suspected misconduct and restrict an entry where justified.</p><p>Instructions for each round will explain permitted collaboration and tools. Retain relevant evidence if you want to challenge a technical result or misconduct finding.</p></section>
    <section><h2>Decisions and appeals</h2><p>Your status page and decision emails report registration decisions. Qualifier scheduling, credentials and results are separate communications. To question a decision, report an error or request an appeal, email <a href="mailto:team@amshq.in">team@amshq.in</a> from your registered address and include your reference and supporting details.</p><p>AMS will provide an appeal opportunity for an automated elimination and communicate the applicable deadline with the decision. If no deadline has been published, contact the team promptly; do not assume that the opportunity has expired.</p></section>
    <section><h2>Your work and documents</h2><p>You retain ownership of your submitted work and documents. You permit AMS to access and use them as needed to evaluate and administer your entry, check integrity and resolve disputes. This does not grant sponsors unrestricted access or transfer ownership of your work. Separate publication or sponsor-sharing permissions will be requested where needed.</p></section>
    <section><h2>Withdrawing and contacting us</h2><p>You can request withdrawal or correction by contacting <a href="mailto:team@amshq.in">team@amshq.in</a>. Data access, consent withdrawal and deletion requests follow the privacy policy. Keep access links and any competition credentials private.</p></section>
    <section><h2>Availability and applicable law</h2><p>If a service interruption affects your submission or participation, contact the team with your reference and the time of the problem. AMS will assess the issue and communicate any remedy or revised arrangements. These terms do not exclude rights or remedies that applicable law does not allow to be excluded.</p><p>These terms are governed by the laws applicable in India. Disputes may be brought before a court or authority with lawful jurisdiction. Contact AMS first where practical so we can try to resolve the issue.</p></section>
    <section><h2>Version history</h2><p>This version was published on 14 September 2026. Registration records store the version accepted. Later material changes will have a new version and will not silently replace the terms recorded for an earlier submission.</p></section>
  </LegalPage>;
}
