import type { Metadata } from "next";
import LegalPage from "@/components/legal/LegalPage";
import { PRIVACY_VERSION, SUPPORT_EMAIL, PARTNERS_EMAIL } from "@/content/legal";
export const metadata: Metadata = { title: "Privacy policy | Ascent", description: "How AMS uses and protects Ascent registration and reminder data." };

export default function PrivacyPage() {
  return <LegalPage title="Privacy policy" version={PRIVACY_VERSION}>
    <section><h2>Who is responsible</h2><p>Algorithms &amp; Mathematics Society (AMS), Mumbai, organises Ascent ’26 and operates this registration website. Contact <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> for privacy requests, candidate support or general help. Sponsorship and partnership enquiries go to <a href={`mailto:${PARTNERS_EMAIL}`}>{PARTNERS_EMAIL}</a>.</p></section>
    <section><h2>What we collect and why</h2><ul>
      <li><strong>Registration:</strong> your name, email, phone, institution, education stage, study level, graduation year and resume link. Optional fields include a transcript link, Codeforces handle, LinkedIn profile and GitHub profile. We use these details to review your entry, determine your qualification path, organise participation and contact you about the competition.</li>
      <li><strong>Reminders:</strong> your email and request time, used to send the registration opening reminder you ask for.</li>
      <li><strong>Status access:</strong> the email you submit, short-lived access credentials and request times, used to confirm control of your registered mailbox and show your entry status.</li>
      <li><strong>Consent and administration:</strong> the notice and terms versions you accepted, timestamps, your reference, decisions and review records. We use these to administer the event, handle corrections and resolve disputes.</li>
      <li><strong>Security:</strong> request metadata, IP-based rate-limit identifiers and bot-verification results. Cloudflare Turnstile processes browser and network signals to help prevent automated submissions. Hosting and service providers may retain their own security logs.</li>
    </ul><p>A Google Drive link lets authorised organisers open the document you choose to share. Check its contents and sharing settings before submitting. Do not include identity documents or unrelated sensitive information in your resume.</p></section>
    <section><h2>Who can receive the data</h2><p>Access is limited to authorised AMS organisers and service providers needed to run the event. The website uses Vercel for hosting, Google Firebase and Firestore for storage and staff authentication, Cloudflare for bot protection, and Resend for transactional email when configured. These services may process data outside India.</p><p>Approved and waitlisted entries may be transferred to AMS Access, the AMS competition platform, for participant records and competition access. Exam software, proctoring and competition telemetry will have their own instructions and notices before use.</p><p>Competition consent does not permit sponsor sharing, recruitment marketing or a public candidate profile. Sharing with a sponsor requires a separate, named and revocable opt-in. We do not sell the registration list. We may disclose information where required by applicable law.</p></section>
    <section><h2>Your choices</h2><p>Registration requires the information needed to administer your entry and your affirmative participation consent. Optional profile and transcript fields can be left blank. Choosing “Notify me” asks for a registration reminder only. Essential entry, access and decision emails are separate from marketing.</p><p>You can ask to correct your details, withdraw from the event, withdraw consent, obtain a copy of your data or delete it by emailing <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Use your registered email and include your reference if you have it. We may need to verify your identity before acting. You do not need an account to make a request.</p><p>Withdrawing participation consent may prevent us from continuing your entry. We will explain any information that must be retained for legal obligations, security investigations or a dispute. Withdrawal does not undo processing already completed lawfully.</p></section>
    <section><h2>Retention and security</h2><p>We retain event records while administering Ascent and resolving related requests and disputes. Our normal review point is 365 days after registration. Records no longer needed are removed through an organiser review; this is not a promise of automatic deletion on a fixed day. Reminder-only data is reviewed after the registration window closes. Short-lived access tokens stop working at expiry even if a security record has not yet been removed.</p><p>Server access controls restrict personal information and email queues. Candidate status uses an emailed link and a temporary browser session. Keep that link private and close the session on a shared device. We cannot guarantee that any internet service is completely secure.</p></section>
    <section><h2>Browser storage and third-party services</h2><p>We use browser storage and cookies for essential functions such as staff authentication and temporary status access. Turnstile may use browser signals and essential challenge storage. This website does not use advertising cookies. External Google Drive documents and linked services follow their providers’ policies.</p><p>Provider information: <a href="https://www.cloudflare.com/privacypolicy/" rel="noreferrer">Cloudflare privacy policy</a>, <a href="https://resend.com/legal/privacy-policy" rel="noreferrer">Resend privacy policy</a>, <a href="https://policies.google.com/privacy" rel="noreferrer">Google privacy policy</a>, and <a href="https://vercel.com/legal/privacy-policy" rel="noreferrer">Vercel privacy policy</a>.</p></section>
    <section><h2>Applicants under 18</h2><p>If you are under 18, ask a parent or guardian to contact <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> before submitting personal information, so AMS can arrange the appropriate permission and participation process. Do not send identity documents through the public registration form.</p></section>
    <section><h2>Questions, complaints and changes</h2><p>Send privacy concerns to <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> with the subject “Ascent privacy request”. We aim to respond within 30 days and will tell you if more time or verification is needed. You may use the complaint routes available under applicable law.</p><p>This version applies from its publication date. Material changes will be published with a new version, and new consent will be requested where needed. <a href="/privacy/v1">Legacy consent records labelled v1</a> do not show that this notice was presented earlier.</p></section>
  </LegalPage>;
}
